server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://13.60.241.8:3306/iot_p  # 数据库连接 URL
    username: root                                  # 数据库用户名
    password: 123456                  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver     # MySQL 驱动类

  jpa:
    hibernate:
      ddl-auto: update  # 自动创建/更新数据库表结构
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true      # 显示 SQL 日志

